<?php

namespace App\Console\Commands;

use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

use Aic\Hub\Foundation\AbstractCommand as BaseCommand;

class CreateSwaggerDocs extends BaseCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'docs:swagger
                            {appUrl? : The root URL to use for the documentation. Defaults to APP_URL}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate swagger documentation for API endpoints';

    protected $appUrl;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {

        $appUrl = config("app.url");

        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        if ($this->argument('appUrl'))
        {

            $this->appUrl = $this->argument('appUrl');

        }

        $doc = "{\n";
        $doc .= "  \"swagger\": \"2.0\",\n";
        $doc .= "  \"info\": {\n";
        $doc .= "    \"title\": \"Art Institution of Chicago API\",\n";
        $doc .= "    \"description\": \"An API for an aggregator of Art Institute of Chicago data\",\n";
        $doc .= "    \"termsOfService\": \"\",\n";
        $doc .= "    \"contact\": {\n";
        $doc .= "      \"email\": \"museumtechnology@artic.edu\"\n";
        $doc .= "    },\n";
        $doc .= "    \"license\": {\n";
        $doc .= "      \"name\": \"\"\n";
        $doc .= "    },\n";
        $doc .= "    \"version\": \"1.0.0\"\n";
        $doc .= "  },\n";
        $doc .= "  \"host\": \"{{ $host }}\",\n";
        $doc .= "  \"basePath\": \"/api/v1\",\n";
        $doc .= "  \"schemes\": [\n";
        $doc .= "    \"http\"\n";
        $doc .= "  ],\n";
        $doc .= "  \"paths\": {\n";

        // Collections
        $doc .= \App\Models\Collections\Artwork::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Agent::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\ArtworkType::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Category::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\AgentType::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Place::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Gallery::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Exhibition::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Image::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Video::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Link::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Sound::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Collections\Text::instance()->swaggerDoc($this->appUrl);

        // Shop
        $doc .= \App\Models\Shop\Category::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Shop\Product::instance()->swaggerDoc($this->appUrl);

        // Events
        $doc .= \App\Models\Membership\LegacyEvent::instance()->swaggerDoc($this->appUrl);
        //$doc .= \App\Models\Membership\TicketedEvent::instance()->swaggerDoc($this->appUrl);

        // Mobile
        $doc .= \App\Models\Mobile\Tour::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Mobile\TourStop::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Mobile\Sound::instance()->swaggerDoc($this->appUrl);

        // Digital Scholarly Catalogs
        $doc .= \App\Models\Dsc\Publication::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Dsc\Section::instance()->swaggerDoc($this->appUrl);

        // Static Archive
        $doc .= \App\Models\StaticArchive\Site::instance()->swaggerDoc($this->appUrl);

        // Archive
        $doc .= \App\Models\Archive\ArchiveImage::instance()->swaggerDoc($this->appUrl);

        // Library
        $doc .= \App\Models\Library\Material::instance()->swaggerDoc($this->appUrl);
        $doc .= \App\Models\Library\Term::instance()->swaggerDoc($this->appUrl);

        //$doc .= "> Generated by `php artisan docs:swagger` on " .Carbon::now() ."\n";

        Storage::disk('local')->put('swagger.json', $doc);

    }

}
