<?php

namespace App\Transformers\Outbound\Collections;

use App\Transformers\Outbound\Collections\Asset as BaseTransformer;

class Image extends BaseTransformer
{

    protected function getAssetFields()
    {
        return [
            'content' => [
                'doc' => 'Text of or URL to the contents of this asset',
                'type' => 'string',
                'elasticsearch' => [
                    'default' => true,
                ],
                'value' => function ($item) {
                    return $item->content ?? null;
                },
            ],
            'iiif_url' => [
                'doc' => 'IIIF URL of this image',
                'type' => 'url',
                'elasticsearch' => 'keyword',
            ],
            'width' => [
                'doc' => 'Native width of the image',
                'type' => 'number',
                'elasticsearch' => 'integer',
                'value' => function ($item) {
                    return $item->width ?? null;
                },
            ],
            'height' => [
                'doc' => 'Native height of the image',
                'type' => 'number',
                'elasticsearch' => 'integer',
                'value' => function ($item) {
                    return $item->height ?? null;
                },
            ],
            'lqip' => [
                'doc' => 'Low-quality image placeholder (LQIP). Currently a 5x5-constrained, base64-encoded GIF.',
                'type' => 'text',
                'elasticsearch' => [
                    'mapping' => [
                        'enabled' => false, // Exclude from indexing, retrievable via _source
                    ],
                ],
                'value' => function ($item) {
                    return $item->metadata->lqip ?? null;
                },
            ],
            'colorfulness' => [
                'doc' => 'Unbounded positive float representing an abstract measure of colorfulness.',
                'type' => 'float',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'scaled_float',
                        'scaling_factor' => 10000,
                    ],
                ],
                'value' => function ($item) {
                    return $item->metadata->colorfulness ?? null;
                },
            ],
            'color' => [
                'doc' => 'Dominant color of this image in HSL',
                'type' => 'object',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'object',
                        'properties' => [
                            'population' => ['type' => 'integer'],
                            'percentage' => ['type' => 'float'],
                            'h' => ['type' => 'integer'],
                            's' => ['type' => 'integer'],
                            'l' => ['type' => 'integer'],
                        ],
                    ],
                ],
                'value' => function ($item) {
                    return $item->metadata->color ?? null;
                },
            ],
            'fingerprint' => [
                'doc' => 'Image hashes: aHash, dHash, pHash, wHash',
                'type' => 'object',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'object',
                        'properties' => [
                            'ahash' => ['type' => 'keyword'],
                            'dhash' => ['type' => 'keyword'],
                            'phash' => ['type' => 'keyword'],
                            'whash' => ['type' => 'keyword'],
                        ],
                    ],
                ],
                'value' => function ($item) {
                    return array_filter([
                        'ahash' => $item->metadata->ahash ?? null,
                        'dhash' => $item->metadata->dhash ?? null,
                        'phash' => $item->metadata->phash ?? null,
                        'whash' => $item->metadata->whash ?? null,
                    ]) ?: null;
                },
            ],
            'ahash' => [
                // TODO: define `elasticsearch` mapping
                'doc' => 'Hash values: hash_0, hash_1, hash_2, hash_3
                                       hash_4, hash_5, hash_6, hash_7, 
                                       hash_8, hash_9, hash_10, hash_11,
                                       hash_12, hash_13, hash_14, hash_15,
                                       hash_16, hash_17, hash_18, hash_19,
                                       hash_20, hash_21, hash_22, hash_23,
                                       hash_24, hash_25, hash_26, hash_27,
                                       hash_28, hash_29, hash_30, hash_31,
                                       hash_32, hash_33, hash_34, hash_35,
                                       hash_36, hash_37, hash_38, hash_39,
                                       hash_40, hash_41, hash_42, hash_43,
                                       hash_44, hash_45, hash_46, hash_47,
                                       hash_48, hash_49, hash_50, hash_51,
                                       hash_52, hash_53, hash_54, hash_55,
                                       hash_56, hash_57, hash_58, hash_59,
                                       hash_60, hash_61, hash_62, hash_63',
                'type' => 'object',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'object',
                        'properties' => [
                            'hash_0' => ['type' => 'keyword'],
                            'hash_1' => ['type' => 'keyword'],
                            'hash_2' => ['type' => 'keyword'],
                            'hash_3' => ['type' => 'keyword'],
                            'hash_4' => ['type' => 'keyword'],
                            'hash_5' => ['type' => 'keyword'],
                            'hash_6' => ['type' => 'keyword'],
                            'hash_7' => ['type' => 'keyword'],
                            'hash_8' => ['type' => 'keyword'],
                            'hash_9' => ['type' => 'keyword'],
                            'hash_10' => ['type' => 'keyword'],
                            'hash_11' => ['type' => 'keyword'],
                            'hash_12' => ['type' => 'keyword'],
                            'hash_13' => ['type' => 'keyword'],
                            'hash_14' => ['type' => 'keyword'],
                            'hash_15' => ['type' => 'keyword'],
                            'hash_16' => ['type' => 'keyword'],
                            'hash_17' => ['type' => 'keyword'],
                            'hash_18' => ['type' => 'keyword'],
                            'hash_19' => ['type' => 'keyword'],
                            'hash_20' => ['type' => 'keyword'],
                            'hash_21' => ['type' => 'keyword'],
                            'hash_22' => ['type' => 'keyword'],
                            'hash_23' => ['type' => 'keyword'],
                            'hash_24' => ['type' => 'keyword'],
                            'hash_25' => ['type' => 'keyword'],
                            'hash_26' => ['type' => 'keyword'],
                            'hash_27' => ['type' => 'keyword'],
                            'hash_28' => ['type' => 'keyword'],
                            'hash_29' => ['type' => 'keyword'],
                            'hash_30' => ['type' => 'keyword'],
                            'hash_31' => ['type' => 'keyword'],
                            'hash_32' => ['type' => 'keyword'],
                            'hash_33' => ['type' => 'keyword'],
                            'hash_34' => ['type' => 'keyword'],
                            'hash_35' => ['type' => 'keyword'],
                            'hash_36' => ['type' => 'keyword'],
                            'hash_37' => ['type' => 'keyword'],
                            'hash_38' => ['type' => 'keyword'],
                            'hash_39' => ['type' => 'keyword'],
                            'hash_40' => ['type' => 'keyword'],
                            'hash_41' => ['type' => 'keyword'],
                            'hash_42' => ['type' => 'keyword'],
                            'hash_43' => ['type' => 'keyword'],
                            'hash_44' => ['type' => 'keyword'],
                            'hash_45' => ['type' => 'keyword'],
                            'hash_46' => ['type' => 'keyword'],
                            'hash_47' => ['type' => 'keyword'],
                            'hash_48' => ['type' => 'keyword'],
                            'hash_49' => ['type' => 'keyword'],
                            'hash_50' => ['type' => 'keyword'],
                            'hash_51' => ['type' => 'keyword'],
                            'hash_52' => ['type' => 'keyword'],
                            'hash_53' => ['type' => 'keyword'],
                            'hash_54' => ['type' => 'keyword'],
                            'hash_55' => ['type' => 'keyword'],
                            'hash_56' => ['type' => 'keyword'],
                            'hash_57' => ['type' => 'keyword'],
                            'hash_58' => ['type' => 'keyword'],
                            'hash_59' => ['type' => 'keyword'],
                            'hash_60' => ['type' => 'keyword'],
                            'hash_61' => ['type' => 'keyword'],
                            'hash_62' => ['type' => 'keyword'],
                            'hash_63' => ['type' => 'keyword'],
                        ],
                    ],
                ],
                'value' => function ($item) {
                    if (empty($item->metadata->ahash)) {
                        return;
                    }
                    
                    // TODO: separate these into `hash_*` fields
                    // cast to object
                    $hashes = hexToBoolArray($item->metadata->ahash);
                    foreach ($hashes as $key=>$value){
                        // $string = '\" hash_' . strval($key) . "\" : ";
                        $hashes[$key] = (object)$value;
                    }

                    // separate these into `hash_*` fields
                    return array_filter([
                        'hash_0' => $hashes[0] ?? null,
                        'hash_1' => $hashes[1] ?? null,
                        'hash_2' => $hashes[2] ?? null,
                        'hash_3' => $hashes[3] ?? null,
                        'hash_4' => $hashes[4] ?? null,
                        'hash_5' => $hashes[5] ?? null,
                        'hash_6' => $hashes[6] ?? null,
                        'hash_7' => $hashes[7] ?? null,
                        'hash_8' => $hashes[8] ?? null,
                        'hash_9' => $hashes[9] ?? null,
                        'hash_10' => $hashes[10] ?? null,
                        'hash_11' => $hashes[11] ?? null,
                        'hash_12' => $hashes[12] ?? null,
                        'hash_13' => $hashes[13] ?? null,
                        'hash_14' => $hashes[14] ?? null,
                        'hash_15' => $hashes[15] ?? null,
                        'hash_16' => $hashes[16] ?? null,
                        'hash_17' => $hashes[17] ?? null,
                        'hash_18' => $hashes[18] ?? null,
                        'hash_19' => $hashes[19] ?? null,
                        'hash_20' => $hashes[20] ?? null,
                        'hash_21' => $hashes[21] ?? null,
                        'hash_22' => $hashes[22] ?? null,
                        'hash_23' => $hashes[23] ?? null,
                        'hash_24' => $hashes[24] ?? null,
                        'hash_25' => $hashes[25] ?? null,
                        'hash_26' => $hashes[26] ?? null,
                        'hash_27' => $hashes[27] ?? null,
                        'hash_28' => $hashes[28] ?? null,
                        'hash_29' => $hashes[29] ?? null,
                        'hash_30' => $hashes[30] ?? null,
                        'hash_31' => $hashes[31] ?? null,
                        'hash_32' => $hashes[32] ?? null,
                        'hash_33' => $hashes[33] ?? null,
                        'hash_34' => $hashes[34] ?? null,
                        'hash_35' => $hashes[35] ?? null,
                        'hash_36' => $hashes[36] ?? null,
                        'hash_37' => $hashes[37] ?? null,
                        'hash_38' => $hashes[38] ?? null,
                        'hash_39' => $hashes[39] ?? null,
                        'hash_40' => $hashes[40] ?? null,
                        'hash_41' => $hashes[41] ?? null,
                        'hash_42' => $hashes[42] ?? null,
                        'hash_43' => $hashes[43] ?? null,
                        'hash_44' => $hashes[44] ?? null,
                        'hash_45' => $hashes[45] ?? null,
                        'hash_46' => $hashes[46] ?? null,
                        'hash_47' => $hashes[47] ?? null,
                        'hash_48' => $hashes[48] ?? null,
                        'hash_49' => $hashes[49] ?? null,
                        'hash_50' => $hashes[50] ?? null,
                        'hash_51' => $hashes[51] ?? null,
                        'hash_52' => $hashes[52] ?? null,
                        'hash_53' => $hashes[53] ?? null,
                        'hash_54' => $hashes[54] ?? null,
                        'hash_55' => $hashes[55] ?? null,
                        'hash_56' => $hashes[56] ?? null,
                        'hash_57' => $hashes[57] ?? null,
                        'hash_58' => $hashes[58] ?? null,
                        'hash_59' => $hashes[59] ?? null,
                        'hash_60' => $hashes[60] ?? null,
                        'hash_61' => $hashes[61] ?? null,
                        'hash_62' => $hashes[62] ?? null,
                        'hash_63' => $hashes[63] ?? null,
                    ]) ?: null;
                },
            ],
            'dhash' => [
                // TODO: define `elasticsearch` mapping
                'doc' => 'Hash values: hash_0, hash_1, hash_2, hash_3
                                       hash_4, hash_5, hash_6, hash_7, 
                                       hash_8, hash_9, hash_10, hash_11,
                                       hash_12, hash_13, hash_14, hash_15,
                                       hash_16, hash_17, hash_18, hash_19,
                                       hash_20, hash_21, hash_22, hash_23,
                                       hash_24, hash_25, hash_26, hash_27,
                                       hash_28, hash_29, hash_30, hash_31,
                                       hash_32, hash_33, hash_34, hash_35,
                                       hash_36, hash_37, hash_38, hash_39,
                                       hash_40, hash_41, hash_42, hash_43,
                                       hash_44, hash_45, hash_46, hash_47,
                                       hash_48, hash_49, hash_50, hash_51,
                                       hash_52, hash_53, hash_54, hash_55,
                                       hash_56, hash_57, hash_58, hash_59,
                                       hash_60, hash_61, hash_62, hash_63',
                'type' => 'object',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'object',
                        'properties' => [
                            'hash_0' => ['type' => 'keyword'],
                            'hash_1' => ['type' => 'keyword'],
                            'hash_2' => ['type' => 'keyword'],
                            'hash_3' => ['type' => 'keyword'],
                            'hash_4' => ['type' => 'keyword'],
                            'hash_5' => ['type' => 'keyword'],
                            'hash_6' => ['type' => 'keyword'],
                            'hash_7' => ['type' => 'keyword'],
                            'hash_8' => ['type' => 'keyword'],
                            'hash_9' => ['type' => 'keyword'],
                            'hash_10' => ['type' => 'keyword'],
                            'hash_11' => ['type' => 'keyword'],
                            'hash_12' => ['type' => 'keyword'],
                            'hash_13' => ['type' => 'keyword'],
                            'hash_14' => ['type' => 'keyword'],
                            'hash_15' => ['type' => 'keyword'],
                            'hash_16' => ['type' => 'keyword'],
                            'hash_17' => ['type' => 'keyword'],
                            'hash_18' => ['type' => 'keyword'],
                            'hash_19' => ['type' => 'keyword'],
                            'hash_20' => ['type' => 'keyword'],
                            'hash_21' => ['type' => 'keyword'],
                            'hash_22' => ['type' => 'keyword'],
                            'hash_23' => ['type' => 'keyword'],
                            'hash_24' => ['type' => 'keyword'],
                            'hash_25' => ['type' => 'keyword'],
                            'hash_26' => ['type' => 'keyword'],
                            'hash_27' => ['type' => 'keyword'],
                            'hash_28' => ['type' => 'keyword'],
                            'hash_29' => ['type' => 'keyword'],
                            'hash_30' => ['type' => 'keyword'],
                            'hash_31' => ['type' => 'keyword'],
                            'hash_32' => ['type' => 'keyword'],
                            'hash_33' => ['type' => 'keyword'],
                            'hash_34' => ['type' => 'keyword'],
                            'hash_35' => ['type' => 'keyword'],
                            'hash_36' => ['type' => 'keyword'],
                            'hash_37' => ['type' => 'keyword'],
                            'hash_38' => ['type' => 'keyword'],
                            'hash_39' => ['type' => 'keyword'],
                            'hash_40' => ['type' => 'keyword'],
                            'hash_41' => ['type' => 'keyword'],
                            'hash_42' => ['type' => 'keyword'],
                            'hash_43' => ['type' => 'keyword'],
                            'hash_44' => ['type' => 'keyword'],
                            'hash_45' => ['type' => 'keyword'],
                            'hash_46' => ['type' => 'keyword'],
                            'hash_47' => ['type' => 'keyword'],
                            'hash_48' => ['type' => 'keyword'],
                            'hash_49' => ['type' => 'keyword'],
                            'hash_50' => ['type' => 'keyword'],
                            'hash_51' => ['type' => 'keyword'],
                            'hash_52' => ['type' => 'keyword'],
                            'hash_53' => ['type' => 'keyword'],
                            'hash_54' => ['type' => 'keyword'],
                            'hash_55' => ['type' => 'keyword'],
                            'hash_56' => ['type' => 'keyword'],
                            'hash_57' => ['type' => 'keyword'],
                            'hash_58' => ['type' => 'keyword'],
                            'hash_59' => ['type' => 'keyword'],
                            'hash_60' => ['type' => 'keyword'],
                            'hash_61' => ['type' => 'keyword'],
                            'hash_62' => ['type' => 'keyword'],
                            'hash_63' => ['type' => 'keyword'],
                        ],
                    ],
                ],
                'value' => function ($item) {
                    if (empty($item->metadata->dhash)) {
                        return;
                    }
                    
                    // TODO: separate these into `hash_*` fields
                    // cast to object
                    $hashes = hexToBoolArray($item->metadata->dhash);
                    foreach ($hashes as $key=>$value){
                        // $string = '\" hash_' . strval($key) . "\" : ";
                        $hashes[$key] = (object)$value;
                    }

                    // separate these into `hash_*` fields
                    return array_filter([
                        'hash_0' => $hashes[0] ?? null,
                        'hash_1' => $hashes[1] ?? null,
                        'hash_2' => $hashes[2] ?? null,
                        'hash_3' => $hashes[3] ?? null,
                        'hash_4' => $hashes[4] ?? null,
                        'hash_5' => $hashes[5] ?? null,
                        'hash_6' => $hashes[6] ?? null,
                        'hash_7' => $hashes[7] ?? null,
                        'hash_8' => $hashes[8] ?? null,
                        'hash_9' => $hashes[9] ?? null,
                        'hash_10' => $hashes[10] ?? null,
                        'hash_11' => $hashes[11] ?? null,
                        'hash_12' => $hashes[12] ?? null,
                        'hash_13' => $hashes[13] ?? null,
                        'hash_14' => $hashes[14] ?? null,
                        'hash_15' => $hashes[15] ?? null,
                        'hash_16' => $hashes[16] ?? null,
                        'hash_17' => $hashes[17] ?? null,
                        'hash_18' => $hashes[18] ?? null,
                        'hash_19' => $hashes[19] ?? null,
                        'hash_20' => $hashes[20] ?? null,
                        'hash_21' => $hashes[21] ?? null,
                        'hash_22' => $hashes[22] ?? null,
                        'hash_23' => $hashes[23] ?? null,
                        'hash_24' => $hashes[24] ?? null,
                        'hash_25' => $hashes[25] ?? null,
                        'hash_26' => $hashes[26] ?? null,
                        'hash_27' => $hashes[27] ?? null,
                        'hash_28' => $hashes[28] ?? null,
                        'hash_29' => $hashes[29] ?? null,
                        'hash_30' => $hashes[30] ?? null,
                        'hash_31' => $hashes[31] ?? null,
                        'hash_32' => $hashes[32] ?? null,
                        'hash_33' => $hashes[33] ?? null,
                        'hash_34' => $hashes[34] ?? null,
                        'hash_35' => $hashes[35] ?? null,
                        'hash_36' => $hashes[36] ?? null,
                        'hash_37' => $hashes[37] ?? null,
                        'hash_38' => $hashes[38] ?? null,
                        'hash_39' => $hashes[39] ?? null,
                        'hash_40' => $hashes[40] ?? null,
                        'hash_41' => $hashes[41] ?? null,
                        'hash_42' => $hashes[42] ?? null,
                        'hash_43' => $hashes[43] ?? null,
                        'hash_44' => $hashes[44] ?? null,
                        'hash_45' => $hashes[45] ?? null,
                        'hash_46' => $hashes[46] ?? null,
                        'hash_47' => $hashes[47] ?? null,
                        'hash_48' => $hashes[48] ?? null,
                        'hash_49' => $hashes[49] ?? null,
                        'hash_50' => $hashes[50] ?? null,
                        'hash_51' => $hashes[51] ?? null,
                        'hash_52' => $hashes[52] ?? null,
                        'hash_53' => $hashes[53] ?? null,
                        'hash_54' => $hashes[54] ?? null,
                        'hash_55' => $hashes[55] ?? null,
                        'hash_56' => $hashes[56] ?? null,
                        'hash_57' => $hashes[57] ?? null,
                        'hash_58' => $hashes[58] ?? null,
                        'hash_59' => $hashes[59] ?? null,
                        'hash_60' => $hashes[60] ?? null,
                        'hash_61' => $hashes[61] ?? null,
                        'hash_62' => $hashes[62] ?? null,
                        'hash_63' => $hashes[63] ?? null,
                    ]) ?: null;
                },
            ],
            'phash' => [
                // TODO: define `elasticsearch` mapping
                'doc' => 'Hash values: hash_0, hash_1, hash_2, hash_3
                                       hash_4, hash_5, hash_6, hash_7, 
                                       hash_8, hash_9, hash_10, hash_11,
                                       hash_12, hash_13, hash_14, hash_15,
                                       hash_16, hash_17, hash_18, hash_19,
                                       hash_20, hash_21, hash_22, hash_23,
                                       hash_24, hash_25, hash_26, hash_27,
                                       hash_28, hash_29, hash_30, hash_31,
                                       hash_32, hash_33, hash_34, hash_35,
                                       hash_36, hash_37, hash_38, hash_39,
                                       hash_40, hash_41, hash_42, hash_43,
                                       hash_44, hash_45, hash_46, hash_47,
                                       hash_48, hash_49, hash_50, hash_51,
                                       hash_52, hash_53, hash_54, hash_55,
                                       hash_56, hash_57, hash_58, hash_59,
                                       hash_60, hash_61, hash_62, hash_63',
                'type' => 'object',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'object',
                        'properties' => [
                            'hash_0' => ['type' => 'keyword'],
                            'hash_1' => ['type' => 'keyword'],
                            'hash_2' => ['type' => 'keyword'],
                            'hash_3' => ['type' => 'keyword'],
                            'hash_4' => ['type' => 'keyword'],
                            'hash_5' => ['type' => 'keyword'],
                            'hash_6' => ['type' => 'keyword'],
                            'hash_7' => ['type' => 'keyword'],
                            'hash_8' => ['type' => 'keyword'],
                            'hash_9' => ['type' => 'keyword'],
                            'hash_10' => ['type' => 'keyword'],
                            'hash_11' => ['type' => 'keyword'],
                            'hash_12' => ['type' => 'keyword'],
                            'hash_13' => ['type' => 'keyword'],
                            'hash_14' => ['type' => 'keyword'],
                            'hash_15' => ['type' => 'keyword'],
                            'hash_16' => ['type' => 'keyword'],
                            'hash_17' => ['type' => 'keyword'],
                            'hash_18' => ['type' => 'keyword'],
                            'hash_19' => ['type' => 'keyword'],
                            'hash_20' => ['type' => 'keyword'],
                            'hash_21' => ['type' => 'keyword'],
                            'hash_22' => ['type' => 'keyword'],
                            'hash_23' => ['type' => 'keyword'],
                            'hash_24' => ['type' => 'keyword'],
                            'hash_25' => ['type' => 'keyword'],
                            'hash_26' => ['type' => 'keyword'],
                            'hash_27' => ['type' => 'keyword'],
                            'hash_28' => ['type' => 'keyword'],
                            'hash_29' => ['type' => 'keyword'],
                            'hash_30' => ['type' => 'keyword'],
                            'hash_31' => ['type' => 'keyword'],
                            'hash_32' => ['type' => 'keyword'],
                            'hash_33' => ['type' => 'keyword'],
                            'hash_34' => ['type' => 'keyword'],
                            'hash_35' => ['type' => 'keyword'],
                            'hash_36' => ['type' => 'keyword'],
                            'hash_37' => ['type' => 'keyword'],
                            'hash_38' => ['type' => 'keyword'],
                            'hash_39' => ['type' => 'keyword'],
                            'hash_40' => ['type' => 'keyword'],
                            'hash_41' => ['type' => 'keyword'],
                            'hash_42' => ['type' => 'keyword'],
                            'hash_43' => ['type' => 'keyword'],
                            'hash_44' => ['type' => 'keyword'],
                            'hash_45' => ['type' => 'keyword'],
                            'hash_46' => ['type' => 'keyword'],
                            'hash_47' => ['type' => 'keyword'],
                            'hash_48' => ['type' => 'keyword'],
                            'hash_49' => ['type' => 'keyword'],
                            'hash_50' => ['type' => 'keyword'],
                            'hash_51' => ['type' => 'keyword'],
                            'hash_52' => ['type' => 'keyword'],
                            'hash_53' => ['type' => 'keyword'],
                            'hash_54' => ['type' => 'keyword'],
                            'hash_55' => ['type' => 'keyword'],
                            'hash_56' => ['type' => 'keyword'],
                            'hash_57' => ['type' => 'keyword'],
                            'hash_58' => ['type' => 'keyword'],
                            'hash_59' => ['type' => 'keyword'],
                            'hash_60' => ['type' => 'keyword'],
                            'hash_61' => ['type' => 'keyword'],
                            'hash_62' => ['type' => 'keyword'],
                            'hash_63' => ['type' => 'keyword'],
                        ],
                    ],
                ],
                'value' => function ($item) {
                    if (empty($item->metadata->phash)) {
                        return;
                    }
                    
                    // TODO: separate these into `hash_*` fields
                    // cast to object
                    $hashes = hexToBoolArray($item->metadata->phash);
                    foreach ($hashes as $key=>$value){
                        // $string = '\" hash_' . strval($key) . "\" : ";
                        $hashes[$key] = (object)$value;
                    }

                    // separate these into `hash_*` fields
                    return array_filter([
                        'hash_0' => $hashes[0] ?? null,
                        'hash_1' => $hashes[1] ?? null,
                        'hash_2' => $hashes[2] ?? null,
                        'hash_3' => $hashes[3] ?? null,
                        'hash_4' => $hashes[4] ?? null,
                        'hash_5' => $hashes[5] ?? null,
                        'hash_6' => $hashes[6] ?? null,
                        'hash_7' => $hashes[7] ?? null,
                        'hash_8' => $hashes[8] ?? null,
                        'hash_9' => $hashes[9] ?? null,
                        'hash_10' => $hashes[10] ?? null,
                        'hash_11' => $hashes[11] ?? null,
                        'hash_12' => $hashes[12] ?? null,
                        'hash_13' => $hashes[13] ?? null,
                        'hash_14' => $hashes[14] ?? null,
                        'hash_15' => $hashes[15] ?? null,
                        'hash_16' => $hashes[16] ?? null,
                        'hash_17' => $hashes[17] ?? null,
                        'hash_18' => $hashes[18] ?? null,
                        'hash_19' => $hashes[19] ?? null,
                        'hash_20' => $hashes[20] ?? null,
                        'hash_21' => $hashes[21] ?? null,
                        'hash_22' => $hashes[22] ?? null,
                        'hash_23' => $hashes[23] ?? null,
                        'hash_24' => $hashes[24] ?? null,
                        'hash_25' => $hashes[25] ?? null,
                        'hash_26' => $hashes[26] ?? null,
                        'hash_27' => $hashes[27] ?? null,
                        'hash_28' => $hashes[28] ?? null,
                        'hash_29' => $hashes[29] ?? null,
                        'hash_30' => $hashes[30] ?? null,
                        'hash_31' => $hashes[31] ?? null,
                        'hash_32' => $hashes[32] ?? null,
                        'hash_33' => $hashes[33] ?? null,
                        'hash_34' => $hashes[34] ?? null,
                        'hash_35' => $hashes[35] ?? null,
                        'hash_36' => $hashes[36] ?? null,
                        'hash_37' => $hashes[37] ?? null,
                        'hash_38' => $hashes[38] ?? null,
                        'hash_39' => $hashes[39] ?? null,
                        'hash_40' => $hashes[40] ?? null,
                        'hash_41' => $hashes[41] ?? null,
                        'hash_42' => $hashes[42] ?? null,
                        'hash_43' => $hashes[43] ?? null,
                        'hash_44' => $hashes[44] ?? null,
                        'hash_45' => $hashes[45] ?? null,
                        'hash_46' => $hashes[46] ?? null,
                        'hash_47' => $hashes[47] ?? null,
                        'hash_48' => $hashes[48] ?? null,
                        'hash_49' => $hashes[49] ?? null,
                        'hash_50' => $hashes[50] ?? null,
                        'hash_51' => $hashes[51] ?? null,
                        'hash_52' => $hashes[52] ?? null,
                        'hash_53' => $hashes[53] ?? null,
                        'hash_54' => $hashes[54] ?? null,
                        'hash_55' => $hashes[55] ?? null,
                        'hash_56' => $hashes[56] ?? null,
                        'hash_57' => $hashes[57] ?? null,
                        'hash_58' => $hashes[58] ?? null,
                        'hash_59' => $hashes[59] ?? null,
                        'hash_60' => $hashes[60] ?? null,
                        'hash_61' => $hashes[61] ?? null,
                        'hash_62' => $hashes[62] ?? null,
                        'hash_63' => $hashes[63] ?? null,
                    ]) ?: null;
                },
            ],
            'whash' => [
                // TODO: define `elasticsearch` mapping
                'doc' => 'Hash values: hash_0, hash_1, hash_2, hash_3
                                       hash_4, hash_5, hash_6, hash_7, 
                                       hash_8, hash_9, hash_10, hash_11,
                                       hash_12, hash_13, hash_14, hash_15,
                                       hash_16, hash_17, hash_18, hash_19,
                                       hash_20, hash_21, hash_22, hash_23,
                                       hash_24, hash_25, hash_26, hash_27,
                                       hash_28, hash_29, hash_30, hash_31,
                                       hash_32, hash_33, hash_34, hash_35,
                                       hash_36, hash_37, hash_38, hash_39,
                                       hash_40, hash_41, hash_42, hash_43,
                                       hash_44, hash_45, hash_46, hash_47,
                                       hash_48, hash_49, hash_50, hash_51,
                                       hash_52, hash_53, hash_54, hash_55,
                                       hash_56, hash_57, hash_58, hash_59,
                                       hash_60, hash_61, hash_62, hash_63',
                'type' => 'object',
                'elasticsearch' => [
                    'mapping' => [
                        'type' => 'object',
                        'properties' => [
                            'hash_0' => ['type' => 'keyword'],
                            'hash_1' => ['type' => 'keyword'],
                            'hash_2' => ['type' => 'keyword'],
                            'hash_3' => ['type' => 'keyword'],
                            'hash_4' => ['type' => 'keyword'],
                            'hash_5' => ['type' => 'keyword'],
                            'hash_6' => ['type' => 'keyword'],
                            'hash_7' => ['type' => 'keyword'],
                            'hash_8' => ['type' => 'keyword'],
                            'hash_9' => ['type' => 'keyword'],
                            'hash_10' => ['type' => 'keyword'],
                            'hash_11' => ['type' => 'keyword'],
                            'hash_12' => ['type' => 'keyword'],
                            'hash_13' => ['type' => 'keyword'],
                            'hash_14' => ['type' => 'keyword'],
                            'hash_15' => ['type' => 'keyword'],
                            'hash_16' => ['type' => 'keyword'],
                            'hash_17' => ['type' => 'keyword'],
                            'hash_18' => ['type' => 'keyword'],
                            'hash_19' => ['type' => 'keyword'],
                            'hash_20' => ['type' => 'keyword'],
                            'hash_21' => ['type' => 'keyword'],
                            'hash_22' => ['type' => 'keyword'],
                            'hash_23' => ['type' => 'keyword'],
                            'hash_24' => ['type' => 'keyword'],
                            'hash_25' => ['type' => 'keyword'],
                            'hash_26' => ['type' => 'keyword'],
                            'hash_27' => ['type' => 'keyword'],
                            'hash_28' => ['type' => 'keyword'],
                            'hash_29' => ['type' => 'keyword'],
                            'hash_30' => ['type' => 'keyword'],
                            'hash_31' => ['type' => 'keyword'],
                            'hash_32' => ['type' => 'keyword'],
                            'hash_33' => ['type' => 'keyword'],
                            'hash_34' => ['type' => 'keyword'],
                            'hash_35' => ['type' => 'keyword'],
                            'hash_36' => ['type' => 'keyword'],
                            'hash_37' => ['type' => 'keyword'],
                            'hash_38' => ['type' => 'keyword'],
                            'hash_39' => ['type' => 'keyword'],
                            'hash_40' => ['type' => 'keyword'],
                            'hash_41' => ['type' => 'keyword'],
                            'hash_42' => ['type' => 'keyword'],
                            'hash_43' => ['type' => 'keyword'],
                            'hash_44' => ['type' => 'keyword'],
                            'hash_45' => ['type' => 'keyword'],
                            'hash_46' => ['type' => 'keyword'],
                            'hash_47' => ['type' => 'keyword'],
                            'hash_48' => ['type' => 'keyword'],
                            'hash_49' => ['type' => 'keyword'],
                            'hash_50' => ['type' => 'keyword'],
                            'hash_51' => ['type' => 'keyword'],
                            'hash_52' => ['type' => 'keyword'],
                            'hash_53' => ['type' => 'keyword'],
                            'hash_54' => ['type' => 'keyword'],
                            'hash_55' => ['type' => 'keyword'],
                            'hash_56' => ['type' => 'keyword'],
                            'hash_57' => ['type' => 'keyword'],
                            'hash_58' => ['type' => 'keyword'],
                            'hash_59' => ['type' => 'keyword'],
                            'hash_60' => ['type' => 'keyword'],
                            'hash_61' => ['type' => 'keyword'],
                            'hash_62' => ['type' => 'keyword'],
                            'hash_63' => ['type' => 'keyword'],
                        ],
                    ],
                ],
                'value' => function ($item) {
                    if (empty($item->metadata->whash)) {
                        return;
                    }
                    
                    // TODO: separate these into `hash_*` fields
                    // cast to object
                    $hashes = hexToBoolArray($item->metadata->whash);
                    foreach ($hashes as $key=>$value){
                        // $string = '\" hash_' . strval($key) . "\" : ";
                        $hashes[$key] = (object)$value;
                    }

                    // separate these into `hash_*` fields
                    return array_filter([
                        'hash_0' => $hashes[0] ?? null,
                        'hash_1' => $hashes[1] ?? null,
                        'hash_2' => $hashes[2] ?? null,
                        'hash_3' => $hashes[3] ?? null,
                        'hash_4' => $hashes[4] ?? null,
                        'hash_5' => $hashes[5] ?? null,
                        'hash_6' => $hashes[6] ?? null,
                        'hash_7' => $hashes[7] ?? null,
                        'hash_8' => $hashes[8] ?? null,
                        'hash_9' => $hashes[9] ?? null,
                        'hash_10' => $hashes[10] ?? null,
                        'hash_11' => $hashes[11] ?? null,
                        'hash_12' => $hashes[12] ?? null,
                        'hash_13' => $hashes[13] ?? null,
                        'hash_14' => $hashes[14] ?? null,
                        'hash_15' => $hashes[15] ?? null,
                        'hash_16' => $hashes[16] ?? null,
                        'hash_17' => $hashes[17] ?? null,
                        'hash_18' => $hashes[18] ?? null,
                        'hash_19' => $hashes[19] ?? null,
                        'hash_20' => $hashes[20] ?? null,
                        'hash_21' => $hashes[21] ?? null,
                        'hash_22' => $hashes[22] ?? null,
                        'hash_23' => $hashes[23] ?? null,
                        'hash_24' => $hashes[24] ?? null,
                        'hash_25' => $hashes[25] ?? null,
                        'hash_26' => $hashes[26] ?? null,
                        'hash_27' => $hashes[27] ?? null,
                        'hash_28' => $hashes[28] ?? null,
                        'hash_29' => $hashes[29] ?? null,
                        'hash_30' => $hashes[30] ?? null,
                        'hash_31' => $hashes[31] ?? null,
                        'hash_32' => $hashes[32] ?? null,
                        'hash_33' => $hashes[33] ?? null,
                        'hash_34' => $hashes[34] ?? null,
                        'hash_35' => $hashes[35] ?? null,
                        'hash_36' => $hashes[36] ?? null,
                        'hash_37' => $hashes[37] ?? null,
                        'hash_38' => $hashes[38] ?? null,
                        'hash_39' => $hashes[39] ?? null,
                        'hash_40' => $hashes[40] ?? null,
                        'hash_41' => $hashes[41] ?? null,
                        'hash_42' => $hashes[42] ?? null,
                        'hash_43' => $hashes[43] ?? null,
                        'hash_44' => $hashes[44] ?? null,
                        'hash_45' => $hashes[45] ?? null,
                        'hash_46' => $hashes[46] ?? null,
                        'hash_47' => $hashes[47] ?? null,
                        'hash_48' => $hashes[48] ?? null,
                        'hash_49' => $hashes[49] ?? null,
                        'hash_50' => $hashes[50] ?? null,
                        'hash_51' => $hashes[51] ?? null,
                        'hash_52' => $hashes[52] ?? null,
                        'hash_53' => $hashes[53] ?? null,
                        'hash_54' => $hashes[54] ?? null,
                        'hash_55' => $hashes[55] ?? null,
                        'hash_56' => $hashes[56] ?? null,
                        'hash_57' => $hashes[57] ?? null,
                        'hash_58' => $hashes[58] ?? null,
                        'hash_59' => $hashes[59] ?? null,
                        'hash_60' => $hashes[60] ?? null,
                        'hash_61' => $hashes[61] ?? null,
                        'hash_62' => $hashes[62] ?? null,
                        'hash_63' => $hashes[63] ?? null,
                    ]) ?: null;
                },
            ],
            
        ];
    }
}
