<?php

namespace App\Console\Commands\Docs;

use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class CreateFieldsDocs extends AbstractDocCommand
{

    protected $signature = 'docs:fields';

    protected $description = 'Generate documentation for all the fields on each endpoint';

    public function handle()
    {
        $doc = '';

        foreach ($this->getCategories() as $namespace => $heading)
        {
            $doc .= "## ${heading}\n\n";

            foreach ($this->getModelsForNamespace($namespace) as $model)
            {
                $doc .= $model::instance()->docFields();
            }
        }

        $doc .= '_Generated by `php artisan docs:fields` on ' . Carbon::now() . "_\n";

        Storage::disk('local')->put('FIELDS.md', $doc);
    }

}
