<?php

namespace App\Console\Commands\Docs;

use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class CreateEndpointDocs extends AbstractDocCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'docs:endpoints
                            {appUrl? : The root URL to use for the documentation. Defaults to APP_URL}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate documentation for API endpoints';

    protected $appUrl;

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        if ($this->argument('appUrl'))
        {
            $this->appUrl = $this->argument('appUrl');
        }

        $doc = '';

        foreach ($this->getCategories() as $namespace => $heading)
        {
            $doc .= "# ${heading}\n\n";

            foreach ($this->getModelsForNamespace($namespace) as $model)
            {
                $doc .= $model::instance()->docEndpoints($this->appUrl);
            }
        }

        $doc .= "> Generated by `php artisan docs:endpoints` on " . Carbon::now() . "\n";

        Storage::disk('local')->put('ENDPOINTS.md', $doc);

    }

}
